package ws.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-01-19T11:50:10.590+07:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://soap.ws/", name = "SoapWSServer")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapWSServer {

    @WebMethod
    @RequestWrapper(localName = "getUserName", targetNamespace = "http://soap.ws/", className = "ws.soap.GetUserName")
    @ResponseWrapper(localName = "getUserNameResponse", targetNamespace = "http://soap.ws/", className = "ws.soap.GetUserNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getUserName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
