package ws.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-01-19T11:50:10.629+07:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "SoapWSServerService", 
                  wsdlLocation = "file:/E:/Project%20Blueprint/Transfer_POC/SOAP-Camel/src/main/resources/wsdl/SoapWSServer.wsdl",
                  targetNamespace = "http://soap.ws/") 
public class SoapWSServerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.ws/", "SoapWSServerService");
    public final static QName SoapWSServerPort = new QName("http://soap.ws/", "SoapWSServerPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/Project%20Blueprint/Transfer_POC/SOAP-Camel/src/main/resources/wsdl/SoapWSServer.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SoapWSServerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/Project%20Blueprint/Transfer_POC/SOAP-Camel/src/main/resources/wsdl/SoapWSServer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SoapWSServerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoapWSServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapWSServerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoapWSServerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoapWSServerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoapWSServerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SoapWSServer
     */
    @WebEndpoint(name = "SoapWSServerPort")
    public SoapWSServer getSoapWSServerPort() {
        return super.getPort(SoapWSServerPort, SoapWSServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapWSServer
     */
    @WebEndpoint(name = "SoapWSServerPort")
    public SoapWSServer getSoapWSServerPort(WebServiceFeature... features) {
        return super.getPort(SoapWSServerPort, SoapWSServer.class, features);
    }

}
